### ISSUE TITLE
how to run plain sparql query

### ISSUE THREAD

**Issue by cagdasolgun** [emk/rdf-agraph#10]
``` ruby
repository.query.perform "select * {?s ?p ?o.}"
```

like in https://github.com/phifty/agraph#sparql-and-prolog-queries.

**Comment by abrisse** [comment]
You can use repo#sparql_query (see https://github.com/emk/rdf-agraph/blob/master/lib/rdf/allegro_graph/abstract_repository.rb#L245).

**Comment by abrisse** [comment]
I will update the documentation (https://github.com/emk/rdf-agraph/issues/6)

**Comment by Robino** [comment]
Hello,
Please could you help us, we would like to write this query query.perform ?: 
SELECT ?person WHERE {
?person a foaf:Person.
FILTER NOT EXISTS {?person rdfs:label “Victor Hugo”@fr } }

**Comment by cagdasolgun** [comment]
@Robino  

``` ruby

repository.query.perform "SELECT ?person WHERE {
?person a foaf:Person.
FILTER NOT EXISTS {?person rdfs:label “Victor Hugo”@fr } }"

```

**Comment by ranielli** [comment]
For sparql_query can not?
