### ISSUE TITLE
Can only access the first part of solution after query

### ISSUE THREAD

**Issue by laurensdv** [emk/rdf-agraph#3]
When I perform a query like this only :person is accessible (the first one) and :name isn't (NoMethod error)

repo.build_query do |q|
  q.pattern [:person, RDF.type,  FOAF.Person]
  q.pattern [:person, FOAF.name, :name]
end.run do |solution|
  puts "#{solution.name}: #{solution.person}"
end

**Comment by abrisse** [comment]
Fixed in ca4428155c54b19355539a2979a0365358b33663
