### ISSUE TITLE
different graph patterns

### ISSUE THREAD

**Issue by cagdasolgun** [emk/rdf-agraph#9]
how to use different graph patterns like "FILTER"

i want to implement 

``` sparql
SELECT ?x
WHERE {
   ?x ?y ?z.
   FILTER (REGEX(STR(?z), "some term", "i"))
}
```

**Comment by abrisse** [comment]
Use repo#sparql_query. Please use stackoverflow or email to ask questions. Github is used to highlight bugs, not for support.
